---
language: ruby
cache: bundler
bundler_args: --without system_tests development --full-index
script: bundle exec rake test SPEC_OPTS='--format documentation'
sudo: false
matrix:
  fast_finish: true
  include:
#  - rvm: 1.9.3
#    env: PUPPET_GEM_VERSION="~> 3.0"
#  - rvm: 1.9.3
#    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.10
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.10
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
notifications:
  email: true
